# Generated by Django 4.1.6 on 2023-02-25 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipient',
            old_name='status',
            new_name='opened',
        ),
    ]
