# Generated by Django 4.1.6 on 2023-03-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appuser',
            options={'ordering': ('-id',), 'verbose_name': 'App User', 'verbose_name_plural': 'App Users'},
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='last_name',
        ),
        migrations.AddField(
            model_name='appuser',
            name='user_name',
            field=models.CharField(max_length=254, null=True, verbose_name='user name'),
        ),
    ]
