# Generated by Django 4.1.6 on 2023-02-25 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_status_recipient_opened'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipient',
            name='unique_recipient_per_campaign',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='recipient_list_id',
        ),
        migrations.AddConstraint(
            model_name='recipient',
            constraint=models.UniqueConstraint(fields=('recipient_id', 'email_campaign_id'), name='unique_recipient_per_campaign'),
        ),
    ]
