# Generated by Django 4.1.6 on 2023-03-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_appuser_options_remove_appuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='license',
            field=models.CharField(max_length=12, unique=True, verbose_name='License Key'),
        ),
    ]
