# Generated by Django 4.1.6 on 2023-03-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_appuser_license'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipient',
            name='unique_recipient_per_campaign',
        ),
        migrations.RenameField(
            model_name='recipient',
            old_name='from_user',
            new_name='sender',
        ),
        migrations.AddConstraint(
            model_name='recipient',
            constraint=models.UniqueConstraint(fields=('recipient_id', 'email_campaign_id', 'sender'), name='unique_recipient_per_campaign'),
        ),
    ]
